# Generated by Django 5.2.5 on 2025-09-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='comments',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
