# Generated by Django 5.2.5 on 2025-09-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_content"),
        ("comments", "0002_alter_comments_options_comments_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.post",
            ),
        ),
    ]
