# Generated by Django 5.2.5 on 2025-09-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
