# Generated by Django 5.2.5 on 2025-09-04 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_category_and_more'),
        ('category', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='category.category'),
        ),
    ]
